<a href="https://colab.research.google.com/github/holdenkim/BBGS_2nd/blob/main/BBGS_2_part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#기본문법

In [1]:
s = 'WiseInCompany'
s1 = "WiseInCompany"
s2 ='''WiseInCompany'''
s3= "123"
print(s)
print(s1)
print(s2)
print(s3)


WiseInCompany
WiseInCompany
WiseInCompany
123


In [2]:
a = "Wise"
b ='InCompany'
print(a+b)
print(a*2 + b*3)

WiseInCompany
WiseWiseInCompanyInCompanyInCompany


In [4]:
a[1]

'i'

In [7]:
a[2:4]

'se'

In [10]:
a = [ 1,2,3,4,5]
print(a)
type(a)

[1, 2, 3, 4, 5]


list

In [11]:
print(a[0])

1


In [12]:
print(a[1:3])

[2, 3]


In [13]:
a.append(6)

In [14]:
print(a)

[1, 2, 3, 4, 5, 6]


In [15]:
del a[1]

In [16]:
print(a)

[1, 3, 4, 5, 6]


In [17]:
a = [1,2]
b = [ 2,3,4]

In [18]:
print(a+b)

[1, 2, 2, 3, 4]


In [19]:
t = (1,2,3,4,)

In [20]:
print(t)

(1, 2, 3, 4)


In [21]:
a = (1,2)
b = (3,4,5)
c = a+b
print(c)

(1, 2, 3, 4, 5)


In [22]:
d = a*3
print(d)

(1, 2, 1, 2, 1, 2)


In [23]:
set = {1,2,3,3}

In [24]:
print(set)

{1, 2, 3}


In [25]:
set.add(4)

In [26]:
print(set)

{1, 2, 3, 4}


In [27]:
test = {"a":1, "b":2, "Park":75}

In [29]:
test['Park']

75

In [32]:
money = 401
if money>500:
  print("많다")
elif money>400:
  print("보통")
else:
  print("쬐금")

보통


In [35]:
sum = 0
for i in range(11):
  sum = sum+i
  print(sum)

0
1
3
6
10
15
21
28
36
45
55


In [36]:
list =["a", "b", "C"]
for x in list:
  print(x)

a
b
C


In [37]:
i=0
while i<10:
  print(i)
  i=i+1

0
1
2
3
4
5
6
7
8
9


In [38]:
food = ["apple", "banna", "carot"]
i = 0
while i< len(food):
  print(food[i])
  i=i+1

apple
banna
carot


#넘파이함수

In [39]:
import numpy as np
v1 = np.array([1,2,3,4])

In [40]:
print(v1)

[1 2 3 4]


In [41]:
type(v1)

numpy.ndarray

In [42]:
v1 = np.arange(5)
print(v1)

[0 1 2 3 4]


In [44]:
v2=np.arange(1,10,2, dtype=int)
print(v2)

[1 3 5 7 9]


In [45]:
v3 = np.arange(3.5, 10.5, 2, dtype=float)

In [46]:
print(v3)

[3.5 5.5 7.5 9.5]


In [47]:
v4 = np.arange(1,10,2)**2

In [48]:
print(v4)

[ 1  9 25 49 81]


In [49]:
v1 = np.arange(12)
print(v1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [51]:
v2= v1.reshape(4,3)
print(v2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [52]:
v3 = v1.reshape(2,6)
print(v3)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [53]:
v4 = v1.reshape(3,-1)
print(v4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [56]:
v5 = v1.reshape(2,3,2, order='F')
print(v5)

[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]


#판다스 함수

In [57]:
import pandas as pd
from pandas import Series, DataFrame

In [58]:
a = Series([1,2,3,4])

In [59]:
print(a)

0    1
1    2
2    3
3    4
dtype: int64


In [60]:
print(a.values)

[1 2 3 4]


In [61]:
print(a.index)

RangeIndex(start=0, stop=4, step=1)


In [62]:
a2 = pd.Series([1,3,4,7], index=['a','b','c','d'])

In [63]:
print(a2)

a    1
b    3
c    4
d    7
dtype: int64
