<a href="https://colab.research.google.com/github/holdenkim/BBGS_2nd/blob/main/BBGS_2_part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#기본문법

In [170]:
s = 'WiseInCompany'
s1 = "WiseInCompany"
s2 ='''WiseInCompany'''
s3= "123"
print(s)
print(s1)
print(s2)
print(s3)


WiseInCompany
WiseInCompany
WiseInCompany
123


In [171]:
a = "Wise"
b ='InCompany'
print(a+b)
print(a*2 + b*3)

WiseInCompany
WiseWiseInCompanyInCompanyInCompany


In [172]:
a[1]

'i'

In [173]:
a[2:4]

'se'

In [174]:
a = [ 1,2,3,4,5]
print(a)
type(a)

[1, 2, 3, 4, 5]


list

In [175]:
print(a[0])

1


In [176]:
print(a[1:3])

[2, 3]


In [177]:
a.append(6)

In [178]:
print(a)

[1, 2, 3, 4, 5, 6]


In [179]:
del a[1]

In [180]:
print(a)

[1, 3, 4, 5, 6]


In [181]:
a = [1,2]
b = [ 2,3,4]

In [182]:
print(a+b)

[1, 2, 2, 3, 4]


In [183]:
t = (1,2,3,4,)

In [184]:
print(t)

(1, 2, 3, 4)


In [185]:
a = (1,2)
b = (3,4,5)
c = a+b
print(c)

(1, 2, 3, 4, 5)


In [186]:
d = a*3
print(d)

(1, 2, 1, 2, 1, 2)


In [187]:
set = {1,2,3,3}

In [188]:
print(set)

{1, 2, 3}


In [189]:
set.add(4)

In [190]:
print(set)

{1, 2, 3, 4}


In [191]:
test = {"a":1, "b":2, "Park":75}

In [192]:
test['Park']

75

In [193]:
money = 401
if money>500:
  print("많다")
elif money>400:
  print("보통")
else:
  print("쬐금")

보통


In [194]:
sum = 0
for i in range(11):
  sum = sum+i
  print(sum)

0
1
3
6
10
15
21
28
36
45
55


In [195]:
list =["a", "b", "C"]
for x in list:
  print(x)

a
b
C


In [196]:
i=0
while i<10:
  print(i)
  i=i+1

0
1
2
3
4
5
6
7
8
9


In [197]:
food = ["apple", "banna", "carot"]
i = 0
while i< len(food):
  print(food[i])
  i=i+1

apple
banna
carot


#넘파이함수

In [198]:
import numpy as np
v1 = np.array([1,2,3,4])

In [199]:
print(v1)

[1 2 3 4]


In [200]:
type(v1)

numpy.ndarray

In [201]:
v1 = np.arange(5)
print(v1)

[0 1 2 3 4]


In [202]:
v2=np.arange(1,10,2, dtype=int)
print(v2)

[1 3 5 7 9]


In [203]:
v3 = np.arange(3.5, 10.5, 2, dtype=float)

In [204]:
print(v3)

[3.5 5.5 7.5 9.5]


In [205]:
v4 = np.arange(1,10,2)**2

In [206]:
print(v4)

[ 1  9 25 49 81]


In [207]:
v1 = np.arange(12)
print(v1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [208]:
v2= v1.reshape(4,3)
print(v2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [209]:
v3 = v1.reshape(2,6)
print(v3)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [210]:
v4 = v1.reshape(3,-1)
print(v4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [211]:
v5 = v1.reshape(2,3,2, order='F')
print(v5)

[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]


#판다스 함수

In [212]:
import pandas as pd
from pandas import Series, DataFrame

In [213]:
a = Series([1,2,3,4])

In [214]:
print(a)

0    1
1    2
2    3
3    4
dtype: int64


In [215]:
print(a.values)

[1 2 3 4]


In [216]:
print(a.index)

RangeIndex(start=0, stop=4, step=1)


In [217]:
a2 = pd.Series([1,3,4,7], index=['a','b','c','d'])

In [218]:
print(a2)

a    1
b    3
c    4
d    7
dtype: int64


In [219]:
df = pd.read_csv('EX_GrapeData.csv')

In [220]:
df

continent  brand  size  period price
0           2      2  10.7   47.65   144
1           2      3  14.0   63.13   215
2           2      2   9.0   58.76   105
3           1      1   8.0   34.88    69
4           2      2  10.0   55.53   134
..        ...    ...   ...     ...   ...
58          1      1   5.0   16.66  21.5
59          2      1  21.0   43.00      
60          2      2   5.0   12.00      
61          2      3  13.0   20.00      
62          2      3  31.0   19.00      

[63 rows x 5 columns]

In [221]:
df.head(5)

continent  brand  size  period price
0          2      2  10.7   47.65   144
1          2      3  14.0   63.13   215
2          2      2   9.0   58.76   105
3          1      1   8.0   34.88    69
4          2      2  10.0   55.53   134

In [222]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   continent  63 non-null     int64  
 1   brand      63 non-null     int64  
 2   size       63 non-null     float64
 3   period     63 non-null     float64
 4   price      63 non-null     object 
dtypes: float64(2), int64(2), object(1)
memory usage: 2.6+ KB


In [223]:
df.describe()

continent      brand       size      period
count  63.000000  63.000000  63.000000   63.000000
mean    1.492063   1.888889  11.344444   35.035079
std     0.503953   0.785167   4.741334   18.874799
min     1.000000   1.000000   5.000000   12.000000
25%     1.000000   1.000000   8.250000   21.190000
50%     1.000000   2.000000  11.000000   30.200000
75%     2.000000   2.500000  13.250000   44.700000
max     2.000000   3.000000  31.000000  109.380000

In [224]:
df[1:5]

continent  brand  size  period price
1          2      3  14.0   63.13   215
2          2      2   9.0   58.76   105
3          1      1   8.0   34.88    69
4          2      2  10.0   55.53   134

In [225]:
df[:3]

continent  brand  size  period price
0          2      2  10.7   47.65   144
1          2      3  14.0   63.13   215
2          2      2   9.0   58.76   105

In [226]:
df.loc[0:3,'continent':'brand']

continent  brand
0          2      2
1          2      3
2          2      2
3          1      1

In [227]:
df['price']

0      144
1      215
2      105
3       69
4      134
      ... 
58    21.5
59        
60        
61        
62        
Name: price, Length: 63, dtype: object

In [228]:
df[['price']]

price
0    144
1    215
2    105
3     69
4    134
..   ...
58  21.5
59      
60      
61      
62      

[63 rows x 1 columns]

In [229]:
df[df.columns[[0,2,4]]]

continent  size price
0           2  10.7   144
1           2  14.0   215
2           2   9.0   105
3           1   8.0    69
4           2  10.0   134
..        ...   ...   ...
58          1   5.0  21.5
59          2  21.0      
60          2   5.0      
61          2  13.0      
62          2  31.0      

[63 rows x 3 columns]

In [230]:
df.iloc[1:5, 0:10]

continent  brand  size  period price
1          2      3  14.0   63.13   215
2          2      2   9.0   58.76   105
3          1      1   8.0   34.88    69
4          2      2  10.0   55.53   134

In [231]:
df.at[5, 'price']

'129'

In [232]:
df_columns = df.copy()

In [233]:
df_columns.columns

Index(['continent', 'brand', 'size', 'period', 'price'], dtype='object')

In [234]:
df_test = df_columns[['size', 'period', 'price']]

In [235]:
df_test.head(5)

size  period price
0  10.7   47.65   144
1  14.0   63.13   215
2   9.0   58.76   105
3   8.0   34.88    69
4  10.0   55.53   134

In [236]:
df_columns.rename(columns={'period':'time'}, inplace=True)

In [237]:
df_columns.head(2)

continent  brand  size   time price
0          2      2  10.7  47.65   144
1          2      3  14.0  63.13   215

In [238]:
df_columns.rename(columns={'time':'period'}, inplace=False)

continent  brand  size  period price
0           2      2  10.7   47.65   144
1           2      3  14.0   63.13   215
2           2      2   9.0   58.76   105
3           1      1   8.0   34.88    69
4           2      2  10.0   55.53   134
..        ...    ...   ...     ...   ...
58          1      1   5.0   16.66  21.5
59          2      1  21.0   43.00      
60          2      2   5.0   12.00      
61          2      3  13.0   20.00      
62          2      3  31.0   19.00      

[63 rows x 5 columns]

In [239]:
df_columns.head(2)

continent  brand  size   time price
0          2      2  10.7  47.65   144
1          2      3  14.0  63.13   215

In [240]:
df_columns['growth']= df_columns['size'] / df_columns['time']

In [241]:
df_columns.head(2)

continent  brand  size   time price    growth
0          2      2  10.7  47.65   144  0.224554
1          2      3  14.0  63.13   215  0.221765

In [242]:
del df_columns['growth']

In [243]:
df_columns.head(2)

continent  brand  size   time price
0          2      2  10.7  47.65   144
1          2      3  14.0  63.13   215

continent 1 / brand 1

In [244]:
df_result = df_columns[(df_columns['continent']==1) & (df_columns['brand']==1)]

In [245]:
df_result.head()

continent  brand  size   time price
3           1      1   8.0  34.88    69
11          1      1  10.4  17.67    54
12          1      1   7.4  16.41    39
13          1      1   5.4  12.02  29.5
16          1      1   6.0  23.21    42

size 10 이상, time 은 30 이상

In [246]:
df_result = df_columns[(df_columns['size']>10) & (df_columns['time']>30)]

In [247]:
df_result.head()

continent  brand  size   time price
0          2      2  10.7  47.65   144
1          2      3  14.0  63.13   215
5          2      2  10.5  43.14   129
6          2      2  16.0  54.86   155
7          2      1  15.0  44.14    99

In [248]:
df['brand'].value_counts()

2    24
1    23
3    16
Name: brand, dtype: int64

In [252]:
recode_df = {"brand":{1:1, 2:1, 3:2}}
df_recode1 = df.replace(recode_df)

In [253]:
df_recode1.head(10)

continent  brand  size  period price
0          2      1  10.7   47.65   144
1          2      2  14.0   63.13   215
2          2      1   9.0   58.76   105
3          1      1   8.0   34.88    69
4          2      1  10.0   55.53   134
5          2      1  10.5   43.14   129
6          2      1  16.0   54.86   155
7          2      1  15.0   44.14    99
8          2      1   6.5   17.46  38.5
9          2      1   5.0   21.04  36.5

In [254]:
df_recode1['brand'].value_counts()

1    47
2    16
Name: brand, dtype: int64

In [255]:
df = pd.read_csv("EX_GrapeData.csv")

In [256]:
df.head()

continent  brand  size  period price
0          2      2  10.7   47.65   144
1          2      3  14.0   63.13   215
2          2      2   9.0   58.76   105
3          1      1   8.0   34.88    69
4          2      2  10.0   55.53   134

In [257]:
df_num = df.to_numpy()

In [259]:
df_pd = pd.DataFrame(df_num)

In [260]:
df_pd.head(1)

0  1     2      3    4
0  2  2  10.7  47.65  144

In [263]:
df_pd1 = pd.DataFrame(data = df_num, columns = ['continent', 'brand', 'size', 'period', 'price'])

In [264]:
df_pd1.head(2)

continent brand  size period price
0         2     2  10.7  47.65   144
1         2     3    14  63.13   215